env:
  browser: true
  es2021: true
extends:
  - standard-with-typescript
  - plugin:react/recommended
  - plugin:react-hooks/recommended
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - react-hooks
ignorePatterns:
  - dist
  - demo/public/assets
rules:
  "@typescript-eslint/indent":
    - error
    - 2
    - ignoredNodes:
        - PropertyDefinition[decorators]
        - TSUnionType
        - TSTypeParameterInstantiation
        - TSIntersectionType
